import type { PipelineConversao, PipelineDashboard } from "@/services/usePipelineDashboard";

const ConversionList = ({ title, items }: { title: string; items: PipelineConversao[] }) => <section className="rounded-xl border border-border/25 bg-card/45 p-4"><h2 className="text-xs font-semibold">{title}</h2><div className="mt-4 space-y-3">{items.length === 0 && <p className="text-[10px] text-muted-foreground">Sem dados no período.</p>}{items.slice(0, 8).map((item) => <div key={item.chave}><div className="flex justify-between text-[10px]"><span className="truncate pr-3">{item.chave}</span><span className="font-semibold">{item.taxaConversao}% <span className="text-muted-foreground">({item.total})</span></span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-accent" style={{ width: `${Math.min(100, item.taxaConversao)}%` }} /></div></div>)}</div></section>;

export const PipelineDashboardBreakdowns = ({ data, onOpenBusiness }: { data: PipelineDashboard; onOpenBusiness: (id: number) => void }) => <>
  <div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-4"><ConversionList title="Conversão por etapa" items={data.conversaoPorEtapa} /><ConversionList title="Conversão por funil" items={data.conversaoPorFunil} /><ConversionList title="Conversão por estratégia" items={data.conversaoPorEstrategia} /><ConversionList title="Conversão por responsável" items={data.conversaoPorResponsavel} /></div>
  <div className="mt-3 grid gap-3 lg:grid-cols-3">
    <section className="rounded-xl border border-border/25 bg-card/45 p-4"><h2 className="text-xs font-semibold">Principais motivos de perda</h2><div className="mt-3 space-y-2">{data.principaisMotivosPerda.map((item) => <div key={item.motivoId} className="flex justify-between border-b border-border/15 py-2 text-[10px]"><span>{item.motivo}</span><strong>{item.quantidade} · {item.percentual}%</strong></div>)}</div></section>
    <section className="rounded-xl border border-border/25 bg-card/45 p-4"><h2 className="text-xs font-semibold">Tempo médio por etapa</h2><div className="mt-3 space-y-2">{data.tempoMedioPorEtapa.slice(0, 8).map((item) => <div key={`${item.funil}-${item.etapaId}`} className="flex justify-between border-b border-border/15 py-2 text-[10px]"><span>{item.etapa}<small className="ml-1 text-muted-foreground">· {item.funil}</small></span><strong>{item.mediaDias} dias</strong></div>)}</div></section>
    <section className="rounded-xl border border-border/25 bg-card/45 p-4"><div className="flex justify-between"><h2 className="text-xs font-semibold">Negócios estagnados</h2><span className="text-[10px] text-orange-500">{data.resumo.tarefasAtrasadas} tarefas atrasadas</span></div><div className="mt-3 space-y-2">{data.negociosEstagnados.slice(0, 8).map((item) => <button type="button" key={item.negocioId} onClick={() => onOpenBusiness(item.negocioId)} className="flex w-full justify-between border-b border-border/15 py-2 text-left text-[10px] hover:text-accent"><span>{item.empresa}<small className="block text-muted-foreground">{item.etapa} · {item.responsavel}</small></span><strong className="text-orange-500">{item.diasSemMovimentacao} dias</strong></button>)}</div></section>
  </div>
</>;
