import { useState } from "react";
import { Braces, Save, X } from "lucide-react";
import type { PipelineScript, PipelineScriptCanal, PipelineScriptInput } from "@/services/usePipelineScripts";

const variables = ["{{nome_pessoa}}", "{{nome_empresa}}", "{{nome_responsavel}}", "{{servico_interesse}}", "{{data_reuniao}}"];

interface Props { script?: PipelineScript | null; processing: boolean; onClose: () => void; onSave: (data: PipelineScriptInput) => void }

export const PipelineScriptDialog = ({ script, processing, onClose, onSave }: Props) => {
  const [draft, setDraft] = useState<PipelineScriptInput>({
    nome: script?.nome || "", categoria: script?.categoria || "Prospecção",
    canal: script?.canal || "WHATSAPP", modeloMensagem: script?.modeloMensagem || "", ativo: script?.ativo ?? true,
  });
  const set = <K extends keyof PipelineScriptInput>(key: K, value: PipelineScriptInput[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const valid = draft.nome.trim() && draft.categoria.trim() && draft.modeloMensagem.trim();

  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button type="button" aria-label="Fechar" className="absolute inset-0 bg-black/55 backdrop-blur-sm" onClick={onClose} /><section role="dialog" className="relative z-10 w-full max-w-2xl rounded-2xl border border-border/30 bg-card shadow-2xl"><header className="flex items-center justify-between border-b border-border/20 px-6 py-4"><div><h2 className="text-sm font-semibold">{script ? "Editar script" : "Novo script"}</h2><p className="mt-1 text-[10px] text-muted-foreground">Crie mensagens reutilizáveis com dados do negócio.</p></div><button type="button" onClick={onClose}><X className="h-4 w-4" /></button></header><div className="space-y-4 p-6"><div className="grid gap-3 sm:grid-cols-2"><label className="text-[11px]">Nome<input value={draft.nome} onChange={(event) => set("nome", event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-border/30 bg-background px-3 outline-none" /></label><label className="text-[11px]">Categoria<input value={draft.categoria} onChange={(event) => set("categoria", event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-border/30 bg-background px-3 outline-none" /></label><label className="text-[11px]">Canal<select value={draft.canal} onChange={(event) => set("canal", event.target.value as PipelineScriptCanal)} className="mt-2 h-10 w-full rounded-lg border border-border/30 bg-background px-3 outline-none">{["EMAIL", "WHATSAPP", "TELEFONE", "LINKEDIN", "REUNIAO", "OUTRO"].map((canal) => <option key={canal}>{canal}</option>)}</select></label><label className="flex items-end gap-2 pb-3 text-[11px]"><input type="checkbox" checked={draft.ativo} onChange={(event) => set("ativo", event.target.checked)} />Script ativo</label></div><label className="block text-[11px]">Modelo de mensagem<textarea rows={8} value={draft.modeloMensagem} onChange={(event) => set("modeloMensagem", event.target.value)} className="mt-2 w-full resize-none rounded-lg border border-border/30 bg-background p-3 outline-none" /></label><div><p className="flex items-center gap-1 text-[10px] text-muted-foreground"><Braces className="h-3.5 w-3.5" />Variáveis disponíveis</p><div className="mt-2 flex flex-wrap gap-2">{variables.map((variable) => <button key={variable} type="button" onClick={() => set("modeloMensagem", `${draft.modeloMensagem}${draft.modeloMensagem ? " " : ""}${variable}`)} className="rounded-md bg-accent/10 px-2 py-1 text-[9px] text-accent">{variable}</button>)}</div></div></div><footer className="flex justify-end border-t border-border/20 px-6 py-4"><button type="button" disabled={!valid || processing} onClick={() => onSave(draft)} className="flex h-9 items-center gap-2 rounded-lg bg-accent px-4 text-[11px] font-semibold text-accent-foreground disabled:opacity-50"><Save className="h-3.5 w-3.5" />Salvar script</button></footer></section></div>;
};
